name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release tag name (default libass version)'
        default: ''


jobs:
  build:
    permissions:
      contents: write
    uses: mpvkit/BuildShared/.github/workflows/build.yml@2aa2c4cc38aa8fbf001eeaebaae13de1e14ea24f
    secrets: inherit
    with:
      version: '${{ github.event.inputs.version }}'
      library: 'libass'
